"""Change icmp data

Revision ID: 119742b412d9
Revises: 6543d85cdd83
Create Date: 2020-07-16 23:56:59.140809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119742b412d9'
down_revision = '6543d85cdd83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
