"""top_talkers

Revision ID: 142e6efc2c48
Revises: 95423a1a5cb2
Create Date: 2020-08-05 18:57:35.066052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '142e6efc2c48'
down_revision = '95423a1a5cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('top_talkers', 'dst_ip',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('top_talkers', 'src_ip',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('top_talkers', 'src_ip',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('top_talkers', 'dst_ip',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
