"""Change host column size

Revision ID: 1adfc517b88a
Revises: 4b691189f69b
Create Date: 2020-07-12 11:12:40.415295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1adfc517b88a'
down_revision = '4b691189f69b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('htt_prequest', 'host',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('htt_prequest', 'response_code',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)
    op.add_column('top_talkers', sa.Column('dest_ip', sa.String(length=15), nullable=True))
    op.add_column('top_talkers', sa.Column('src_ip', sa.String(length=15), nullable=True))
    op.drop_column('top_talkers', 'source Ip')
    op.drop_column('top_talkers', 'dest Ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('top_talkers', sa.Column('dest Ip', mysql.VARCHAR(length=15), nullable=True))
    op.add_column('top_talkers', sa.Column('source Ip', mysql.VARCHAR(length=15), nullable=True))
    op.drop_column('top_talkers', 'src_ip')
    op.drop_column('top_talkers', 'dest_ip')
    op.alter_column('htt_prequest', 'response_code',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('htt_prequest', 'host',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
