"""chnging database

Revision ID: 1e9e89155fc1
Revises: 9ecef70686f2
Create Date: 2020-08-06 12:35:45.600602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e9e89155fc1'
down_revision = '9ecef70686f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
