"""changing

Revision ID: 21e0ef0dc429
Revises: 7beba35db512
Create Date: 2020-07-29 15:43:38.818668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e0ef0dc429'
down_revision = '7beba35db512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
