"""changing

Revision ID: 4d6139a79709
Revises: 6f4814f3593f
Create Date: 2020-07-29 14:02:57.821225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6139a79709'
down_revision = '6f4814f3593f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
