"""Change tables

Revision ID: 6543d85cdd83
Revises: 66e5047921dc
Create Date: 2020-07-14 22:09:55.705432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6543d85cdd83'
down_revision = '66e5047921dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tcp_stream')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tcp_stream',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('stream_index', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('value', mysql.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
