"""Change icmp data

Revision ID: 66e5047921dc
Revises: 139a80c1381d
Create Date: 2020-07-14 20:10:41.126572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e5047921dc'
down_revision = '139a80c1381d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('icmp_packet', sa.Column('dest_ip', sa.String(length=15), nullable=True))
    op.add_column('icmp_packet', sa.Column('src_ip', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('icmp_packet', 'src_ip')
    op.drop_column('icmp_packet', 'dest_ip')
    # ### end Alembic commands ###
