"""changing

Revision ID: 6f4814f3593f
Revises: 119742b412d9
Create Date: 2020-07-29 14:02:33.852502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f4814f3593f'
down_revision = '119742b412d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('top_talkers', 'dest_ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('top_talkers', sa.Column('dest_ip', mysql.VARCHAR(length=15), nullable=True))
    # ### end Alembic commands ###
