"""chnging database

Revision ID: 9ecef70686f2
Revises: 142e6efc2c48
Create Date: 2020-08-05 19:36:05.654077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ecef70686f2'
down_revision = '142e6efc2c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
