"""changing

Revision ID: c7b3cc68fb34
Revises: 4d6139a79709
Create Date: 2020-07-29 14:43:28.541997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b3cc68fb34'
down_revision = '4d6139a79709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
